CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
) ENGINE = INNODB;
INSERT INTO users (name, firstname, email)
VALUES ('Farmer', 'Seth', 'apjoip@ahoiphu.ht'),
    ('Sims', 'Mamie', 'boluli@ve.nl'),
    ('Hubbard', 'Andre', 'ivu@ruwa.mw'),
    ('Arnold', 'Gene', 'cika@udaepo.ky'),
    ('Gomez', 'Jennie', 'gofuzakiv@dog.ni'),
    ('Peterson', 'Lela', 'dahwudim@in.bt'),
    ('Harrison', 'Pauline', 'os@bus.lu'),
    ('Spencer', 'Bessie', 'hotkuun@gulned.aq'),
    ('Sherman', 'Beulah', 'gozzaw@usujo.nz'),
    ('Guerrero', 'James', 'wev@fozacem.cy'),
    ('Carroll', 'Ronald', 'cafon@dabaj.ss'),
    ('Singleton', 'Susie', 'kammocin@nanlo.om'),
    ('Townsend', 'Jay', 'woh@sonbeli.fj'),
    ('Daniels', 'Jim', 'dowam@efkev.kp'),
    ('Mathis', 'Bessie', 'fi@ahihamgun.vc'),
    ('Curry', 'Marvin', 'afa@minanje.lk'),
    ('Nichols', 'Sophie', 'bif@safcifob.id'),
    ('Wells', 'Edith', 'me@no.mh'),
    ('Allison', 'Micheal', 'cekozu@husab.co'),
    ('Jimenez', 'Gussie', 'vusbe@ig.sj'),
    ('Gray', 'Terry', 'ku@iri.bm'),
    ('Bridges', 'Louise', 'busavruh@telugki.kn'),
    ('Nichols', 'Birdie', 'mod@ilijil.fo'),
    ('Tucker', 'Lenora', 'dofkowdu@cihizod.cf'),
    ('West', 'Roy', 'urpasol@garim.ht'),
    ('Erickson', 'Ollie', 'uzwo@jidvode.ng'),
    ('Watkins', 'Floyd', 'potove@ekgucov.mk'),
    ('Hardy', 'Tony', 'uvunu@dali.pe'),
    ('Marsh', 'Sophia', 'sof@jod.pr'),
    ('Beck', 'Jayden', 'zulozugo@fodece.com'),
    ('Wilkins', 'Lily', 'tacnu@eko.li'),
    ('Bell', 'Sophie', 'zaredher@fefnez.dm'),
    ('Barton', 'Erik', 'nac@hamempap.cl'),
    ('Byrd', 'Harvey', 'muvhe@set.gov'),
    ('Rogers', 'Bryan', 'conoziuh@ruma.br'),
    ('Stokes', 'Sophia', 'relupga@lolmejvip.org'),
    ('Powers', 'Leah', 'ocwop@zivu.ch'),
    ('Reyes', 'Gerald', 'omi@igivopgah.dj'),
    ('Russell', 'Jason', 'wibci@hiane.bs'),
    ('Watts', 'Gary', 'toz@lufi.bv'),
    ('Romero', 'Rodney', 'pemakej@ado.tf'),
    ('Armstrong', 'Warren', 'dur@picnev.de'),
    ('Quinn', 'Olive', 'mevovuwo@limboror.sd'),
    ('Farmer', 'Eric', 'fij@eba.ki'),
    ('Hayes', 'Lily', 'pauwi@buzudlof.ms'),
    ('Gray', 'Polly', 'mo@ewmibi.pt'),
    ('Harper', 'Eva', 'ni@pasjitid.cc'),
    ('Davis', 'Dylan', 'fidjo@dunevu.ng'),
    ('Cain', 'Olga', 'lefipsum@cilhin.dz'),
    ('Grant', 'Allen', 'laruw@ocbe.pr'),
    ('Park', 'Dominic', 'lujruug@fa.eu'),
    ('Zimmerman', 'Nathan', 'ka@hagaldub.sy'),
    ('Holt', 'Mattie', 'buldap@be.my'),
    ('McLaughlin', 'Joe', 'uva@kuvo.iq'),
    ('Ramsey', 'Bradley', 'fef@ifwan.et'),
    ('Stanley', 'Rachel', 'ucehocjom@rife.tr'),
    ('Copeland', 'Adrian', 'tus@iwsujpa.rs'),
    ('Gregory', 'Mario', 'hocpo@nupzopur.je'),
    ('Townsend', 'Maria', 'kilvumu@mildubep.gg'),
    ('Greene', 'Dylan', 'govidlil@cudirube.jm');